/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatrixIndexRouteImport } from './routes/matrix.index'
import { Route as MatrixIdRouteImport } from './routes/matrix.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixIndexRoute = MatrixIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MatrixRoute,
} as any)
const MatrixIdRoute = MatrixIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MatrixRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/matrix': typeof MatrixRouteWithChildren
  '/register': typeof RegisterRoute
  '/matrix/$id': typeof MatrixIdRoute
  '/matrix/': typeof MatrixIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/matrix/$id': typeof MatrixIdRoute
  '/matrix': typeof MatrixIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/matrix': typeof MatrixRouteWithChildren
  '/register': typeof RegisterRoute
  '/matrix/$id': typeof MatrixIdRoute
  '/matrix/': typeof MatrixIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/matrix'
    | '/register'
    | '/matrix/$id'
    | '/matrix/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home' | '/login' | '/register' | '/matrix/$id' | '/matrix'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/login'
    | '/matrix'
    | '/register'
    | '/matrix/$id'
    | '/matrix/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MatrixRoute: typeof MatrixRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix/': {
      id: '/matrix/'
      path: '/'
      fullPath: '/matrix/'
      preLoaderRoute: typeof MatrixIndexRouteImport
      parentRoute: typeof MatrixRoute
    }
    '/matrix/$id': {
      id: '/matrix/$id'
      path: '/$id'
      fullPath: '/matrix/$id'
      preLoaderRoute: typeof MatrixIdRouteImport
      parentRoute: typeof MatrixRoute
    }
  }
}

interface MatrixRouteChildren {
  MatrixIdRoute: typeof MatrixIdRoute
  MatrixIndexRoute: typeof MatrixIndexRoute
}

const MatrixRouteChildren: MatrixRouteChildren = {
  MatrixIdRoute: MatrixIdRoute,
  MatrixIndexRoute: MatrixIndexRoute,
}

const MatrixRouteWithChildren =
  MatrixRoute._addFileChildren(MatrixRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MatrixRoute: MatrixRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
